export const Menu = [
    {
        id: 1,
        image: "/assets/text.svg",
        title: "STextView Android Library",
        category: "Android",
        link: "https://github.com/smith8h/STextView",
    },
    {
        id: 2,
        image: "/assets/color.svg",
        title: "SColor Android Library",
        category: "Android",
        link: "https://github.com/smith8h/SColor",
    },
    {
        id: 3,
        image: "/assets/filter.svg",
        title: "STextFilter Android Library",
        category: "Android",
        link: "https://github.com/smith8h/STextFilter",
    },
    {
        id: 4,
        image: "/assets/animation.svg",
        title: "SAnimation Android Library",
        category: "Android",
        link: "https://github.com/smith8h/SAnimation",
    },
    {
        id: 5,
        image: "/assets/toast.svg",
        title: "SToast Android Library",
        category: "Android",
        link: "https://github.com/smith8h/SToast",
    },
    {
        id: 6,
        image: "/assets/cover.svg",
        title: "SCoverView Android Library",
        category: "Android",
        link: "https://github.com/smith8h/SCoverView",
    },
    {
        id: 7,
        image: "/assets/report.svg",
        title: "SReporter Android Library",
        category: "Android",
        link: "https://github.com/smith8h/SReporter",
    },
    {
        id: 8,
        image: "/assets/global.svg",
        title: "SConnect Android Library",
        category: "Android",
        link: "https://github.com/smith8h/SConnect",
    },
    {
        id: 9,
        image: "/assets/dialog.svg",
        title: "SDialogs Android Library",
        category: "Android",
        link: "https://github.com/smith8h/SDialogs",
    },
    {
        id: 10,
        image: "/assets/permission.svg",
        title: "SPermissions Android Library",
        category: "Android",
        link: "https://github.com/smith8h/SPermissions",
    },
    {
        id: 11,
        image: "/assets/calc.svg",
        title: "SCalculator (kotlin) Android Library",
        category: "Android",
        link: "https://github.com/smith8h/SCalculator-kotlin",
    },
    {
        id: 12,
        image: "/assets/color.svg",
        title: "SColors Flutter Library",
        category: "Flutter",
        link: "https://github.com/smith8h/scolors-flutter",
    },
    {
        id: 13,
        image: "/assets/toast.svg",
        title: "NaalAlarm Flutter Library",
        category: "Flutter",
        link: "https://github.com/smith8h/naal_alarm",
    },
    {
        id: 14,
        image: "/assets/toast.svg",
        title: "SBadgeView Flutter Library",
        category: "Flutter",
        link: "https://github.com/smith8h/sbadge_view",
    },
    {
        id: 15,
        image: "/assets/report.svg",
        title: "SReporter Flutter Library",
        category: "Flutter",
        link: "https://github.com/smith8h/sbadge_view",
    },
    {
        id: 16,
        image: "/assets/port.svg",
        title: "My Portfolio web Front-End site",
        category: "Web",
        link: "https://github.com/smith8h/Smith-Portfolio",
    },
];
